student-node ~ ➜  cat /etc/alertmanager/alertmanager.yml
global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'slack-notifications'

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/T08SX7JN96G/B08SSA4FQMT/UyxPwfZ6sHEIFU5M' # Replace with your Slack webhook URL
        channel: '#alerts'         # Replace with your Slack channel name
        send_resolved: true
        title: "{{ .CommonAnnotations.summary }}"
        text: "{{ range .Alerts }}*Alert:* {{ .Annotations.description }}\n*Severity:* {{ .Labels.severity }}\n*Instance:* {{ .Labels.instance }}\n{{ end }}"


student-node ~ ➜  

sudo systemctl restart alertmanager

