apiVersion: v1
kind: Pod
metadata:
  name: http-echo
  labels:
    app: http-echo
spec:
  containers:
  - name: http-echo
    image: hashicorp/http-echo
    args:
      - "-text=Hello from Kubernetes!"
    ports:
      - containerPort: 5678
  tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
