name: Terraform Deploy AWS VPC Setup

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        working-directory: ./tf/my_vpc
        run: terraform init

      - name: Terraform Validate
        working-directory: ./tf/my_vpc
        run: terraform validate

      - name: Terraform Plan
        id: plan
        working-directory: ./tf/my_vpc
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        if: github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/main'
        working-directory: ./tf/my_vpc
        run: terraform apply -auto-approve tfplan

      - name: Show Outputs
        working-directory: ./tf/my_vpc
        run: terraform output
